#
# Makefile for Proxy Lab
#
# The Makefile will build the proxy using all .c and .h files found in the
# current directory. It will not be submitted with your code.
#
# If you have additional .c or .h files (e.g. for building a separate test
# program), you can add those files to .tarignore.
#
# Autolab will execute the command "make proxy" on your specific
# Makefile to build your proxy from sources.
#
CC = gcc
CFLAGS = -g -Og -std=c11 -Wall -Wextra -Wpedantic -Wstrict-prototypes \
	 -Wno-unused-parameter -Werror
CPPFLAGS = -I. -MMD -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=700
PARSER_LIB_PATH = /afs/cs.cmu.edu/academic/class/15213-f20/www/labs/proxylab
LDLIBS = -lpthread -lm -lpcre
LDLIBS += -Wl,-rpath,$(PARSER_LIB_PATH)
LDLIBS += -L$(PARSER_LIB_PATH) -lhttp_parser

# For proxylab, LLVM is only used for clang-format
LLVM_PATH =
ifneq (,$(wildcard /usr/lib/llvm-7/bin/))
   LLVM_PATH = /usr/lib/llvm-7/bin/
else
 ifneq (,$(wildcard /usr/local/depot/llvm-7.0/bin/))
   LLVM_PATH = /usr/local/depot/llvm-7.0/bin/
 endif
endif

# Targets to compile
HANDIN_TAR = proxylab-handin.tar
FILES = proxy proxy-dbg $(HANDIN_TAR)
TINY_FILES = tiny/tiny tiny/tiny-static tiny/cgi-bin/adder

# Find files to be used for handin
HANDIN_FILES := $(shell \
  tar cvf /dev/null --exclude-from=.gitignore --exclude-from=.tarignore \
    $$(git ls-files) )

# Filter .c and .h files
SOURCES := $(filter %.c,$(HANDIN_FILES))
DEPS := $(filter %.h,$(HANDIN_FILES))
ifeq ($(SOURCES),)
  $(error No .c files in current directory to make.)
endif

# Default build rule
.PHONY: all
all: $(FILES) $(TINY_FILES)

# Autogenerated rules to build object files
OBJECTS = $(SOURCES:%.c=%.o)
OBJECTS_DBG = $(SOURCES:%.c=%_d.o)

# This is the same as the built-in %.o: %.c rule except for the additional
# -DDEBUG.
%_d.o: %.c
	$(COMPILE.c) -DDEBUG -o $@ $<

-include $(SOURCES:%.c=%.d) $(SOURCES:%.c=%_d.d)

# Link proxy executables
# The built-in %: %.o rule does not work for proxy-dbg.
proxy: $(OBJECTS)
	$(LINK.o) $^ $(LDLIBS) -o $@

proxy-dbg: $(OBJECTS_DBG)
	$(LINK.o) $^ $(LDLIBS) -o $@

# Link tiny helper executables
tiny/tiny: tiny/tiny.o csapp.o
tiny/tiny-static: tiny/tiny-static.o csapp.o
tiny/cgi-bin/adder: tiny/cgi-bin/adder.o

.PHONY: clean
clean:
	-git clean -dfqX

# Include rules for submit, format, etc
FORMAT_FILES = $(SOURCES) $(DEPS)
include helper.mk
